spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: logs/api-local.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 10
  level:
    root: info
    org.msa.item: debug

springdoc:
  default-consumes-media-type: application/json #API 함수에 대해 media-type을 지정하지 않았을 때, 웹 문서에 기본적으로 application/json으로 주고받는 기능이라고 출력하기 위함
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true #url 쿼리 매개변수를 이용해서 swagger-ui에 대한 처리를 활성화하는 설정