spring:
  application:
    name: item-service

logging:
  file:
    name: logs/api.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 10
  level:
    root: info
    org.msa.item: debug
