spring:
  application:
    name: item-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8080

server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans